name: Publish to npm

on:
  push:
    branches:
      - main  # or the branch you want to trigger on

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the package
        run: npm run build

      - name: Bump version and push tag
        id: bump_version
        run: |
          npm version patch  # or minor/major
          git push origin main --tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
